sudo: false
language: elixir

otp_release: '21.1'
elixir: '1.7'

jobs:
  - check formatted
  - test

script:
  - mix test --include stdlib

jobs:
  include:
    - stage: test

    - otp_release: '20.3'
      elixir: '1.5'

    - otp_release: '20.3'
      elixir: '1.6'

    - stage: check formatted
      script: mix format --check-formatted
